name: "\U0001F41B Issue Report: AnalyzeSWSupport"
description: |
  Help us improve AnalyzeSWSupport. 
  Please check for existing issues: [Search existing issues](https://github.ibm.com/log-comprehension/log-diagnosis/issues) before submitting.

labels:
  - "bug"

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Issue Report

        ### Summary
        Briefly describe the issue, including any relevant screenshots.

  - type: textarea
    id: summary
    attributes:
      label: Brief Description
      description: Provide a brief description of the issue, including any relevant screenshots.
      placeholder: Briefly describe the issue.
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ### Expected Behavior
        What did you expect to happen?

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe expected behavior.
      placeholder: Describe expected behavior.
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ### Actual Behavior
        What happened instead?

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe the actual behavior.
      placeholder: Describe the actual behavior.
    validations:
      required: true


  - type: markdown
    attributes:
      value: |
        ### System Information

  - type: input
    id: system-info
    attributes:
      label: System Information
      description: Share your system info (e.g., tool version).
      placeholder: e.g., v1.2.3
    validations:
      required: true

